spring:
  application:
    name: spring-boot-template
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_template
    username: admin
    password: Admin@123
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_EagsnDUHC
          jwk-set-uri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_EagsnDUHC/.well-known/jwks.json
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      read-date-timestamps-as-nanoseconds: false
springdoc:
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    csrf:
      enabled: true